name: Continuous Integration

on:
  push: 
    branches: [main]

jobs:
  check-file:
    run-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 
      
      - name: Check student data file
        shell: cmd
        run: if exist studentdata.txt (echo File exists) else (exit /b 1)
